name: Release Binaries

# Trigger on version tags (e.g., v1.0.0, v1.2.3)
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git describe

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    # Extract version from tag (e.g., v1.0.0 -> 1.0.0)
    - name: Get version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Building version: ${VERSION}"

    # Build binaries for all platforms
    - name: Build binaries
      run: |
        mkdir -p build

        # Function to build for a specific platform
        build_platform() {
          local GOOS=$1
          local GOARCH=$2
          local OUTPUT_NAME="bioproxy-${GOOS}-${GOARCH}"

          echo "Building for ${GOOS}/${GOARCH}..."

          GOOS=$GOOS GOARCH=$GOARCH go build \
            -ldflags "-X main.Version=v${{ steps.version.outputs.version }}" \
            -trimpath \
            -o "build/${OUTPUT_NAME}" \
            ./cmd/bioproxy

          # Calculate SHA256 checksum
          (cd build && sha256sum "${OUTPUT_NAME}" > "${OUTPUT_NAME}.sha256")

          echo "✓ Built: build/${OUTPUT_NAME}"
        }

        # Build for requested platforms
        build_platform "darwin" "arm64"    # Apple Silicon (M1/M2/M3/M4)
        build_platform "linux" "arm64"     # Linux ARM64 (aarch64)
        build_platform "linux" "amd64"     # Linux x86_64

    # List built binaries
    - name: List built binaries
      run: ls -lh build/

    # Create GitHub Release and upload binaries
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          build/bioproxy-darwin-arm64
          build/bioproxy-darwin-arm64.sha256
          build/bioproxy-linux-arm64
          build/bioproxy-linux-arm64.sha256
          build/bioproxy-linux-amd64
          build/bioproxy-linux-amd64.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
